# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  mod_coortime_config = debug
endif

PROJECTS := mod_coortime

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

mod_coortime:
ifneq (,$(mod_coortime_config))
	@echo "==== Building mod_coortime ($(mod_coortime_config)) ===="
	@${MAKE} --no-print-directory -C . -f mod_coortime.make config=$(mod_coortime_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f mod_coortime.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   mod_coortime"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"